#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Load Pre-computed Embeddings to ChromaDB

This script loads embeddings from parquet files (generated by embedding_gen.py)
and stores them in ChromaDB with the same format as vectorstore.py.
"""

import os
import time
import argparse
from pathlib import Path

import chromadb
import numpy as np
import pandas as pd
import pyarrow.parquet as pq
from tqdm import tqdm

from sentinelrag.utils.paths import default_chroma_dir

ChromadbPath = str(default_chroma_dir())


class ParquetToChromaLoader:
    """Load embeddings from parquet files into ChromaDB"""
    
    def __init__(self, collection_name, embeddings_dir, distance='cosine', use_local=False, chroma_path=None):
        """
        Initialize the loader.
        
        Args:
            collection_name: Name for the ChromaDB collection
            embeddings_dir: Directory containing parquet embedding files
            distance: Distance metric ('cosine', 'l2', 'ip')
            use_local: Whether to use existing local collection (if False, recreates)
        """
        # Use PersistentClient to save collections to disk
        self.chroma_path = str(chroma_path or ChromadbPath)
        self.chroma_client = chromadb.PersistentClient(
            path=self.chroma_path,
            settings=chromadb.Settings(
                anonymized_telemetry=False
            )
        )
        self.embeddings_dir = Path(embeddings_dir)
        
        # Check if embeddings directory exists
        if not self.embeddings_dir.exists():
            raise ValueError(f"Embeddings directory does not exist: {embeddings_dir}")
        
        # List all parquet files
        self.parquet_files = sorted(self.embeddings_dir.glob("*.parquet"))
        if not self.parquet_files:
            raise ValueError(f"No parquet files found in {embeddings_dir}")
        
        print(f"Found {len(self.parquet_files)} parquet files in {embeddings_dir}")
        
        # Get or create collection
        collections = self.chroma_client.list_collections()
        collection_exists = any(col.name == collection_name for col in collections)
        
        if collection_exists and use_local:
            print(f"Using existing local chromadb named {collection_name}")
            self.collection = self.chroma_client.get_collection(name=collection_name)
            print(f"Current collection size: {self.collection.count()}")
        else:
            if collection_exists:
                print(f"Deleting existing local chromadb named {collection_name}")
                self.chroma_client.delete_collection(name=collection_name)
            print(f"Creating new chromadb collection named {collection_name}")
            self.collection = self.chroma_client.create_collection(
                name=collection_name, 
                metadata={"hnsw:space": distance}
            )
    
    def load_from_parquet(self, batch_size=5000):
        """
        Load embeddings from parquet files and store to ChromaDB.
        
        Args:
            batch_size: Number of documents to add to ChromaDB at once (default 5000 for optimal performance)
        """
        start_time = time.time()
        current_count = self.collection.count()
        
        # Calculate total documents across all parquet files
        total_docs = 0
        print("Counting total documents in parquet files...")
        for pq_file in self.parquet_files:
            pf = pq.ParquetFile(pq_file)
            total_docs += pf.metadata.num_rows
        
        print(f"Total documents to load: {total_docs}")
        
        if current_count > 0:
            print(f"Already have {current_count} documents in collection")
            if current_count >= total_docs:
                print("Collection already contains all documents. Skipping load.")
                return
        
        docs_processed = 0
        last_report_time = time.time()
        last_report_count = 0
        
        # Process each parquet file
        for file_idx, pq_file in enumerate(self.parquet_files):
            print(f"\n📂 Loading {pq_file.name} ({file_idx + 1}/{len(self.parquet_files)})...")
            
            # Read parquet file using PyArrow (faster than pandas)
            table = pq.read_table(pq_file)
            num_rows = table.num_rows
            print(f"  File contains {num_rows} documents")
            
            # Convert columns once per file (avoid expensive conversions per batch)
            embeddings_array = np.vstack(table['embeddings'].to_numpy()).astype('float32')
            documents_list = table['documents'].to_pylist()
            ids_list = table['ids'].to_pylist()
            metadatas_list = table['metadatas'].to_pylist()
            
            # Process in batches to avoid memory issues
            for i in range(0, num_rows, batch_size):
                batch_end = min(i + batch_size, num_rows)
                
                # Slice pre-converted arrays/lists (much faster than repeated .tolist())
                batch_embeddings = embeddings_array[i:batch_end]
                batch_documents = documents_list[i:batch_end]
                batch_ids = ids_list[i:batch_end]
                batch_metadatas = metadatas_list[i:batch_end]
                
                # Sanitize metadata: remove None values as ChromaDB doesn't support them
                for meta in batch_metadatas:
                     if meta:
                        keys_to_remove = [k for k, v in meta.items() if v is None]
                        for k in keys_to_remove:
                            del meta[k]
                
                # Add to ChromaDB
                self.collection.add(
                    embeddings=batch_embeddings,
                    documents=batch_documents,
                    ids=batch_ids,
                    metadatas=batch_metadatas
                )
                
                docs_processed += batch_end - i
                
                # Progress reporting (reduced frequency for better performance)
                if docs_processed % 5000 < batch_size or docs_processed >= total_docs:
                    elapsed = time.time() - start_time
                    avg_speed = docs_processed / elapsed if elapsed > 0 else 0
                    eta = (total_docs - docs_processed) / avg_speed if avg_speed > 0 else 0
                    
                    print(f"  Loaded: {docs_processed}/{total_docs} "
                          f"({100*docs_processed/total_docs:.1f}%) | "
                          f"Speed: {avg_speed:.1f} docs/s | "
                          f"ETA: {eta/60:.1f} min")
        
        total_time = time.time() - start_time
        avg_speed = docs_processed / total_time if total_time > 0 else 0
        
        print(f"\n✓ Done! Loaded {docs_processed} documents")
        print(f"  Total time: {total_time/60:.2f} min | Avg speed: {avg_speed:.1f} docs/s")
        print(f"  Final collection size: {self.collection.count()}")
        print(f"  (Collection persisted to {self.chroma_path})")
    
    def verify_collection(self, sample_size=5):
        """
        Verify that data was loaded correctly by sampling a few documents.
        
        Args:
            sample_size: Number of documents to sample for verification
        """
        print(f"\n🔍 Verifying collection...")
        print(f"Total documents in collection: {self.collection.count()}")
        
        # Get a few sample documents
        sample_ids = [f'id_{i}' for i in range(min(sample_size, self.collection.count()))]
        results = self.collection.get(ids=sample_ids, include=['documents', 'metadatas', 'embeddings'])
        
        print(f"\nSample documents:")
        for i in range(len(results['ids'])):
            doc_id = results['ids'][i]
            doc_text = results['documents'][i][:100] + "..." if len(results['documents'][i]) > 100 else results['documents'][i]
            metadata = results['metadatas'][i]
            embedding_dim = len(results['embeddings'][i]) if results['embeddings'] else 0
            
            print(f"\n  ID: {doc_id}")
            print(f"  Text: {doc_text}")
            print(f"  Title: {metadata['title']}")
            print(f"  Original ID: {metadata['id']}")
            print(f"  Changed: {metadata['change']}")
            print(f"  Embedding dim: {embedding_dim}")


def check_collection(collection_name, chroma_path=None):
    """Check if a collection exists and return its size"""
    chroma_client = chromadb.PersistentClient(
        path=str(chroma_path or ChromadbPath),
        settings=chromadb.Settings(
            anonymized_telemetry=False
        )
    )
    collections = chroma_client.list_collections()
    print(f"Available collections: {[col.name for col in collections]}")
    
    collection_exists = any(col.name == collection_name for col in collections)
    total_items = 0
    
    if collection_exists:
        collection = chroma_client.get_collection(name=collection_name)
        total_items = collection.count()
        print(f"Collection '{collection_name}' exists, total documents: {total_items}")
        return True, total_items
    else:
        print(f"Collection '{collection_name}' not found")
        return False, total_items


def main():
    parser = argparse.ArgumentParser(
        description='Load pre-computed embeddings from parquet files to ChromaDB'
    )
    parser.add_argument('--embeddings_dir', type=str, default="embeddings/nfcorpusward_contriever_test",
                      help='Directory containing parquet embedding files')
    parser.add_argument('--collection_name', type=str, default=None,
                      help='Name for the ChromaDB collection (defaults to {dataset}_{model}_{score_function})')
    parser.add_argument('--batch_size', type=int, default=500,
                      help='Batch size for loading to ChromaDB (5000-10000 recommended for speed)')
    parser.add_argument('--use_local', action='store_true',
                      help='Use existing collection if it exists (skip recreation)')
    parser.add_argument('--verify', action='store_true',
                      help='Verify collection after loading')
    parser.add_argument('--chroma_dir', type=str, default=ChromadbPath,
                      help='ChromaDB persistence directory')
    
    args = parser.parse_args()
    
    # Parse embeddings directory name to extract dataset, model, and score_function
    # Expected format: {dataset}_{optional_suffix}_{model}_{score_function}
    # Example: msmarco_200k_contriever_cosine
    embeddings_dir_name = Path(args.embeddings_dir).name
    parts = embeddings_dir_name.split('_')
    
    # Try to extract components from directory name
    eval_dataset = None
    eval_model_code = None
    score_function = None
    
    if len(parts) >= 3:
        # Check for score function (usually last part)
        if parts[-1] in ['cosine', 'l2', 'ip']:
            score_function = parts[-1]
            remaining_parts = parts[:-1]
        else:
            remaining_parts = parts
        
        # Check for model (usually second to last or third to last)
        for model in ['contriever', 'contriever-msmarco', 'ance']:
            if model in remaining_parts:
                eval_model_code = model
                model_idx = remaining_parts.index(model)
                # Everything before model is dataset
                if model_idx > 0:
                    eval_dataset = '_'.join(remaining_parts[:model_idx])
                break
    
    # Use detected values with fallback defaults
    eval_dataset = eval_dataset if eval_dataset else 'msmarco'
    eval_model_code = eval_model_code if eval_model_code else 'contriever'
    score_function = score_function if score_function else 'cosine'
    
    # Generate collection name if not provided (same format as vectorstore.py)
    if args.collection_name is None:
        args.collection_name = f"{eval_dataset}_{eval_model_code}_{score_function}"
    
    print(f"{'='*60}")
    print(f"Loading Embeddings to ChromaDB")
    print(f"{'='*60}")
    print(f"Embeddings directory: {args.embeddings_dir}")
    print(f"Detected - Dataset: {eval_dataset}, Model: {eval_model_code}, Score: {score_function}")
    print(f"Collection name: {args.collection_name}")
    print(f"Batch size: {args.batch_size}")
    print(f"{'='*60}\n")
    
    # Check if collection already exists
    exists, count = check_collection(args.collection_name, chroma_path=args.chroma_dir)
    
    # Create loader and load data
    loader = ParquetToChromaLoader(
        collection_name=args.collection_name,
        embeddings_dir=args.embeddings_dir,
        distance=score_function,
        use_local=args.use_local,
        chroma_path=args.chroma_dir,
    )
    
    # Load embeddings
    loader.load_from_parquet(batch_size=args.batch_size)
    
    # Verify if requested
    if args.verify:
        loader.verify_collection()
    
    print(f"\n{'='*60}")
    print("✓ Complete!")
    print(f"{'='*60}")


if __name__ == '__main__':
    main()
